### ISSUE TITLE
Some questions about modeling

### ISSUE THREAD

**Issue by flamewind1** [ZXF1001/ZXF1001.github.io#5]
Dear all.
I am starting a project where I'll have to simulate some real world wind turbines and was wondering if I could get some guidance from you guys. I have a small distributed wind turbine that I would like to simulate in OpenFAST. However, I encountered a problem right at the first step. I have the physical and 3D model of this wind turbine, but the way our wind turbine connects to the hub is quite unique, as shown in the attached image. Therefore, how can I obtain the following data: PitchAxis, StrcTwst, BMassDen, FlpStff, EdgStff? Is there any good method? Can these data be exported from SolidWorks?

Thank you for your help.
![2222](https://github.com/user-attachments/assets/6d677cc0-6b7d-45f4-a4bc-2a828122e3a8)
![1111](https://github.com/user-attachments/assets/adc03703-df35-4aad-bcd5-1e0baff1369a)

**Comment by ZXF1001** [comment]
I am currently researching the simulation of the entire wind farm scale, using the already configured NREW-5MW wind turbine. I have not yet studied how to simulate the wind turbines user defined. Perhaps you can ask questions to researchers related to OpenFAST

**Comment by flamewind1** [comment]
> I am currently researching the simulation of the entire wind farm scale, using the already configured NREW-5MW wind turbine. I have not yet studied how to simulate the wind turbines user defined. Perhaps you can ask questions to researchers related to OpenFAST

I'm sorry for asking the question in the wrong place.Thank you for your response.
